# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
    
    working_directory: ~/SRA

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
   
    branches:
        only:
            - master
            - /feature.*/
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: git submodule init && git submodule update
      - run: mvn clean install

      - save_cache:
          paths:
            - ~/.m2
          key: dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      - run: mvn test

